version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      # Setup SSH deploy keys
      - npm install
  build:
    commands:
      - ls

artifacts:
  files:
    - appspec.yml
    - git-deploy.sh