version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      # Setup SSH deploy keys
      - npm install
  build:
    commands:
      - ls

artifacts:
  files:
    - appspec.json
    - git-deploy.sh